CREATE TABLE T_WORKTIME
(
SEQ_VC VARCHAR2(9) NOT NULL,
WORKCD_VC VARCHAR2(4) NOT NULL,
TIME_NU NUMERIC(5,2) NOT NULL
)
/
INSERT INTO T_WORKTIME (SEQ_VC,WORKCD_VC,TIME_NU) VALUES (35,'A001',1.17);
INSERT INTO T_WORKTIME (SEQ_VC,WORKCD_VC,TIME_NU) VALUES (42,'B003',0.11);
INSERT INTO T_WORKTIME (SEQ_VC,WORKCD_VC,TIME_NU) VALUES (49,'B004',0.83);
INSERT INTO T_WORKTIME (SEQ_VC,WORKCD_VC,TIME_NU) VALUES (56,'A001',0.89) ;
INSERT INTO T_WORKTIME (SEQ_VC,WORKCD_VC,TIME_NU) VALUES (63,'B004',4.13);
INSERT INTO T_WORKTIME (SEQ_VC,WORKCD_VC,TIME_NU) VALUES (70,'B003',0.28);
INSERT INTO T_WORKTIME (SEQ_VC,WORKCD_VC,TIME_NU) VALUES (77,'C002',2.14);
INSERT INTO T_WORKTIME (SEQ_VC,WORKCD_VC,TIME_NU) VALUES (84,'A001',0.77);
INSERT INTO T_WORKTIME (SEQ_VC,WORKCD_VC,TIME_NU) VALUES (91,'B003',4.01);
INSERT INTO T_WORKTIME (SEQ_VC,WORKCD_VC,TIME_NU) VALUES (98,'A001',1.01);
INSERT INTO T_WORKTIME (SEQ_VC,WORKCD_VC,TIME_NU) VALUES (105,'A001',2.34);
INSERT INTO T_WORKTIME (SEQ_VC,WORKCD_VC,TIME_NU) VALUES (112,'C002',1.18);
INSERT INTO T_WORKTIME (SEQ_VC,WORKCD_VC,TIME_NU) VALUES (119,'B004',0.49);
INSERT INTO T_WORKTIME (SEQ_VC,WORKCD_VC,TIME_NU) VALUES (126,'B004',0.24);
INSERT INTO T_WORKTIME (SEQ_VC,WORKCD_VC,TIME_NU) VALUES (133,'C002',1.13);
COMMIT;


성적 목록 샘플


CREATE TABLE T_GREPORT
(
GRADE_VC VARHCAR2(2) NOT NULL, 
SUBJECT_VC VARCHAR2(20) NOT NULL,
POINT_NU NUMBER NOT NULL  
)
/

INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'이순신','수학',85);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'이순신','영어',70);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'이순신','국어',66);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'이순신','물리',78);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'이순신','화학',95);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'무용해','수학',46);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'무용해','영어',88);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'무용해','국어',94);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'무용해','물리',58);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'무용해','화학',87);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'마동탁','수학',68);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'마동탁','영어',59);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'마동탁','국어',87);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'마동탁','물리',95);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'마동탁','화학',94);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'임걱정','수학',46);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'임걱정','영어',88);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'임걱정','국어',94);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'임걱정','물리',58);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'임걱정','화학',87);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'홍길동','수학',68);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'홍길동','영어',59);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'홍길동','국어',87);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'홍길동','물리',95);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (1 ,'홍길동','화학',94);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'이순신','수학',66);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'이순신','영어',89);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'이순신','국어',47);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'이순신','물리',88);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'이순신','화학',85);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'무용해','수학',45);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'무용해','영어',58);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'무용해','국어',36);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'무용해','물리',46);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'무용해','화학',36);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'마동탁','수학',85);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'마동탁','영어',78);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'마동탁','국어',57);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'마동탁','물리',68);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'마동탁','화학',96);                                             
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'임걱정','수학',55);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'임걱정','영어',78);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'임걱정','국어',89);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'임걱정','물리',90);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'임걱정','화학',95);                                                                                                  
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'홍길동','수학',45);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'홍길동','영어',55);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'홍길동','국어',95);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'홍길동','물리',94);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (2 ,'홍길동','화학',88);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'이순신','수학',56);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'이순신','영어',77);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'이순신','국어',45);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'이순신','물리',87);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'이순신','화학',66);                                                                                                      
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'무용해','수학',95);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'무용해','영어',97);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'무용해','국어',95);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'무용해','물리',87);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'무용해','화학',97);                                                                                                     
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'마동탁','수학',67);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'마동탁','영어',84);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'마동탁','국어',66);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'마동탁','물리',54);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'마동탁','화학',48);                                                                                                    
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'임걱정','수학',75);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'임걱정','영어',80);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'임걱정','국어',70);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'임걱정','물리',78);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'임걱정','화학',85);                                                                                                       
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'홍길동','수학',75);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'홍길동','영어',68);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'홍길동','국어',79);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'홍길동','물리',86);
INSERT INTO T_GREPORT ( NAME_VC , GRADE_VC , SUBJECT_VC , POINT_NU) VALUES (3 ,'홍길동','화학',70);
COMMIT;